C:\Users\yukih\OneDrive\Documentos\Bomberman-BackArsw>tree
Listado de rutas de carpetas
El número de serie del volumen es C8BD-1D13
C:.
├───.github
│   └───workflows
└───arsw
    ├───.mvn
    │   └───wrapper
    ├───src
    │   ├───main
    │   │   ├───java
    │   │   │   └───bomberman
    │   │   │       └───arsw
    │   │   │           ├───config
    │   │   │           ├───Controller
    │   │   │           ├───Model
    │   │   │           ├───Service
    │   │   │           ├───Socket
    │   │   │           └───util
    │   │   └───resources
    │   └───test
    │       └───java
    │           └───bomberman
    │               └───arsw
    └───target
        ├───classes
        │   └───bomberman
        │       └───arsw
        │           ├───config
        │           ├───Controller
        │           ├───Model
        │           ├───Service
        │           ├───Socket
        │           └───util
        ├───generated-sources
        │   └───annotations
        ├───generated-test-sources
        │   └───test-annotations
        ├───maven-archiver
        ├───maven-status
        │   └───maven-compiler-plugin
        │       ├───compile
        │       │   └───default-compile
        │       └───testCompile
        │           └───default-testCompile
        ├───site
        │   └───jacoco
        │       ├───bomberman.arsw
        │       ├───bomberman.arsw.config
        │       ├───bomberman.arsw.Controller
        │       ├───bomberman.arsw.Model
        │       ├───bomberman.arsw.Service
        │       ├───bomberman.arsw.Socket
        │       ├───bomberman.arsw.util
        │       └───jacoco-resources
        ├───surefire-reports
        └───test-classes
            └───bomberman
                └───arsw
